openapi: 3.0.3

info:
  title: Dashboard backend API v1
  description: Uses integer product IDs
  version: 1.0.0
  contact:
    name: API Support
    email: allesverloren133@gmail.com

servers:
  - url: http://127.0.0.1:4010
    description: Mock Server

tags:
  - name: products
    description: Everything about products

paths:
  /products:
    get:
      tags:
        - products
      summary: Returns all products
      description: >
        Lists all products (with a `limit` option if needed)
      operationId: listProducts
      parameters:
        - name: limit
          in: query
          description: Limit of items returned
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      $ref: './schemas/ProductInteger.yaml'
