type: object
description: Product with string ID
properties:
  id:
    type: string
    description: ID
  title:
    type: string
    description: Title
  price:
    $ref: './Price.yaml'
required:
  - id
  - title
  - price
