type: object
description: Product with integer ID
properties:
  id:
    type: integer
    description: ID
    minimum: 1
  title:
    type: string
    description: Title
  price:
    $ref: './Price.yaml'
required:
  - id
  - title
  - price
